# Columns of the result dataset
FID = 'fid'
FIELD_ID = 'field_id'
TRACE_TYPE = 'trace_type'
IS_XSRC = 'is_xsrc'
IS_YSRC = 'is_ysrc'
IS_ONLY_XSRC= 'is_only_xsrc'
IS_ONLY_YSRC = 'is_only_ysrc'
DATA = 'data'
DTYPE = 'dtype'
LENGTH = 'length'

N_XSRC = 'n_xsrc'
N_YSRC = 'n_ysrc'
N_TRACES = 'n_traces'
